### ISSUE TITLE
Possibly use Antrl?

### ISSUE THREAD

**Issue by jvanzyl** [verils/gotemplate4j#2]
I've been wanting to try and make a version Helm in Java so I started looking around for gotemplate implementations in Java and here we go! I'm going to give it a try this weekend.

**Comment by verils** [comment]
Sorry I can't give a help.😂 I found the current lexer and parser work just fine, so I've given up to change it.

I think Helm is no more than a template engine with some predefined funcs, and some file handling methods, do you have any progress?
